version: '3.8'

services:
  go-service:
    build: .
    container_name: go-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  atlas:
    image: arigaio/atlas:latest
    restart: "no"
    container_name: atlas
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./infra/atlas/migrations:/migrations
      - ./infra/atlas/atlas.hcl:/app/atlas.hcl
    command: [
      "migrate", "apply",
      "--dir", "file:///migrations",
      "--url", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
    ]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
